remote_theme: akademie-oeffentliches-gesundheitswesen/lehrbuch-theme

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

plugins:
  - jekyll-seo-tag

title: Krisenmanagement - Lehrbuch für den Öffentlichen Gesundheitsdienst

# Aux links for the upper right navigation
aux_links:
  "Lehrbuch auf GitHub":
    - "https://github.com/akademie-oeffentliches-gesundheitswesen/lehrbuch-krisenmanagment"
  "PDF":
    - "pdf/Krisenmanagement-pre-release-v1.pdf"
  "Web-Buch":
    - "https://consortium.github.io/lehrbuch-krisenmanagment/vivliostyle-viewer-2.0.0-pre.10/viewer/#src=https://consortium.github.io/lehrbuch-krisenmanagment/netbuch/krisenmanagement-netbuch.xhtml&bookMode=true&renderAllPages=true"

logo: "/images/akademie.png"

ga_tracking: UA-161871347-1

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 die Autoren. Creative Commons: Namensnennung - Weitergabe unter gleichen Bedingungen 4.0 International (CC BY-SA 4.0) https://creativecommons.org/licenses/by-sa/4.0/deed.de | DOI 10.25815/h0ec-f967"
